addresses = {
    "Avalanche (AVAX)": "0x987da2d7b222a422d6605c66a6e47aeabf3e91c5",
    "Binance Coin (BNB)": "bnb12uygta8tlnhdr3vlgw5rtcwwsrm2qgu6hu3t0h",
    "Bitcoin (BTC)": "1LQSzFZKE5vwiUS94toMG7r5M2nQ4X2muw",
    "Bitcoin Cash (BCH)": "qzhr6lc9r64c3wg3jnndqaxzpyxeghdp2s57w5wgwu",
    "Cardano (ADA)": "DdzFFzCqrht3N125qEXgFCb1KGrcusTaL8dKW7Ep39zpV8919ZKxn6GkWYSEpaPfoY4MyfogozfLUTpVyKdTmnZP6bZSV94Lhv9GuXm9",
    "Dash (DASH)": "Xn5HwktiWJfgKydTDjodBTjJDA6tVxzAho",
    "DigiByte (DGB)": "D97CQ5pV1AukRY1FJTSW3CFkJtUZgdwJq4",
    "Dogecoin (DOGE)": "D5YP7CggUUkS3fu1B7RjhjJ7jvNu6A4Ksx",
    "Ethereum (ETH)": "0x80D3CA7528cF05118131dBa3d7852Db2685c4b9E",
    "Groestlcoin (GRS)": "Fafh4zcRBiZiZ1ZqVgk5u6C1hzWJfSWrBf",
    "Litecoin (LTC)": "LRQ6TBVXsEVPApbCY79bV1d9LR8E7JiuDd",
    "Polkadot (DOT)": "12b7ww2zhuZsMvNgDRTuQaC3sK7wEVyRjoeLdsxHeLCuLyt8",
    "Solana (SOL)": "Feyknn2ehnUc5b9CvgogFS8wehvZzS9FWaxcAANnGz7g",
    "Stellar (XLM)": "GCZI74FS6WJDIQUMIJQBDIOCZMNCBGCWJ6AA6QO45Y5LA7DJ5L2ARCWT",
    "Toncoin (TON)": "UQDdP6a_0IdInRtVbCAMO5cSIU6c1ptVegeKewPltXGJVsGO",
    "Tron (TRX)": "TEivYaNov8LERnBaTJiry8K9m7u46Mxs86",
}
urls = {
    "Avalanche (AVAX)": "https://blockchair.com/avalanche/transaction/",
    "Binance Coin (BNB)": "https://blockchair.com/bnb/transaction/",
    "Bitcoin (BTC)": "https://blockchair.com/bitcoin/transaction/",
    "Bitcoin Cash (BCH)": "https://blockchair.com/bitcoin-cash/transaction/",
    "Cardano (ADA)": "https://blockchair.com/cardano/transaction/",
    "Dash (DASH)": "https://blockchair.com/dash/transaction/",
    "DigiByte (DGB)": "https://blockchair.com/digibyte/transaction/",
    "Dogecoin (DOGE)": "https://blockchair.com/dogecoin/transaction/",
    "Ethereum (ETH)": "https://blockchair.com/ethereum/transaction/",
    "Groestlcoin (GRS)": "https://blockchair.com/groestlcoin/transaction/",
    "Litecoin (LTC)": "https://blockchair.com/litecoin/transaction/",
    "Polkadot (DOT)": "https://blockchair.com/polkadot/transaction/",
    "Solana (SOL)": "https://blockchair.com/solana/transaction/",
    "Stellar (XLM)": "https://blockchair.com/stellar/transaction/",
    "Toncoin (TON)": "https://blockchair.com/ton/transaction/",
    "Tron (TRX)": "https://blockchair.com/tron/transaction/",
}
# List of cryptocurrency names
cryptos = {
    "Avalanche (AVAX)": "Payment/Photos/avalanche (avax).png",
    "Binance Coin (BNB)": "Payment/Photos/binance coin (bnb).png",
    "Bitcoin (BTC)": "Payment/Photos/bitcoin (btc).png",
    "Bitcoin Cash (BCH)": "Payment/Photos/bitcoin cash (bch).png",
    "Cardano (ADA)": "Payment/Photos/cardano (ada).png",
    "Dash (DASH)": "Payment/Photos/dash (dash).png",
    "DigiByte (DGB)": "Payment/Photos/digibyte (dgb).png",
    "Dogecoin (DOGE)": "Payment/Photos/dogecoin (doge).png",
    "Ethereum (ETH)": "Payment/Photos/ethereum (eth).png",
    "Groestlcoin (GRS)": "Payment/Photos/groestlcoin (grs).png",
    "Litecoin (LTC)": "Payment/Photos/litecoin (ltc).png",
    "Polkadot (DOT)": "Payment/Photos/polkadot (dot).png",
    "Solana (SOL)": "Payment/Photos/solana (sol).png",
    "Stellar (XLM)": "Payment/Photos/stellar (xlm).png",
    "Toncoin (TON)": "Payment/Photos/toncoin (ton).png",
    "Tron (TRX)": "Payment/Photos/tron (trx).png",
}
