from Payment.iap_variables import the_coins

addresses = {
    the_coins[0]: "0x987da2d7b222a422d6605c66a6e47aeabf3e91c5",
    the_coins[1]: "bnb12uygta8tlnhdr3vlgw5rtcwwsrm2qgu6hu3t0h",
    the_coins[2]: "1LQSzFZKE5vwiUS94toMG7r5M2nQ4X2muw",
    the_coins[3]: "qzhr6lc9r64c3wg3jnndqaxzpyxeghdp2s57w5wgwu",
    the_coins[4]: "DdzFFzCqrht3N125qEXgFCb1KGrcusTaL8dKW7Ep39zpV8919ZKxn6GkWYSEpaPfoY4MyfogozfLUTpVyKdTmnZP6bZSV94Lhv9GuXm9",
    the_coins[5]: "Xn5HwktiWJfgKydTDjodBTjJDA6tVxzAho",
    the_coins[6]: "D97CQ5pV1AukRY1FJTSW3CFkJtUZgdwJq4",
    the_coins[7]: "D5YP7CggUUkS3fu1B7RjhjJ7jvNu6A4Ksx",
    the_coins[8]: "0x80D3CA7528cF05118131dBa3d7852Db2685c4b9E",
    the_coins[9]: "Fafh4zcRBiZiZ1ZqVgk5u6C1hzWJfSWrBf",
    the_coins[10]: "LRQ6TBVXsEVPApbCY79bV1d9LR8E7JiuDd",
    the_coins[11]: "12b7ww2zhuZsMvNgDRTuQaC3sK7wEVyRjoeLdsxHeLCuLyt8",
    the_coins[12]: "Feyknn2ehnUc5b9CvgogFS8wehvZzS9FWaxcAANnGz7g",
    the_coins[13]: "GCZI74FS6WJDIQUMIJQBDIOCZMNCBGCWJ6AA6QO45Y5LA7DJ5L2ARCWT",
    the_coins[14]: "UQDdP6a_0IdInRtVbCAMO5cSIU6c1ptVegeKewPltXGJVsGO",
    the_coins[15]: "TEivYaNov8LERnBaTJiry8K9m7u46Mxs86",
}
urls = {
    the_coins[0]: "https://blockchair.com/avalanche/transaction/",
    the_coins[1]: "https://blockchair.com/bnb/transaction/",
    the_coins[2]: "https://blockchair.com/bitcoin/transaction/",
    the_coins[3]: "https://blockchair.com/bitcoin-cash/transaction/",
    the_coins[4]: "https://blockchair.com/cardano/transaction/",
    the_coins[5]: "https://blockchair.com/dash/transaction/",
    the_coins[6]: "https://blockchair.com/digibyte/transaction/",
    the_coins[7]: "https://blockchair.com/dogecoin/transaction/",
    the_coins[8]: "https://blockchair.com/ethereum/transaction/",
    the_coins[9]: "https://blockchair.com/groestlcoin/transaction/",
    the_coins[10]: "https://blockchair.com/litecoin/transaction/",
    the_coins[11]: "https://blockchair.com/polkadot/transaction/",
    the_coins[12]: "https://blockchair.com/solana/transaction/",
    the_coins[13]: "https://blockchair.com/stellar/transaction/",
    the_coins[14]: "https://blockchair.com/ton/transaction/",
    the_coins[15]: "https://blockchair.com/tron/transaction/",
}
# List of cryptocurrency names
cryptos = {
    the_coins[0]: "Payment/Photos/avalanche (avax).png",
    the_coins[1]: "Payment/Photos/binance coin (bnb).png",
    the_coins[2]: "Payment/Photos/bitcoin (btc).png",
    the_coins[3]: "Payment/Photos/bitcoin cash (bch).png",
    the_coins[4]: "Payment/Photos/cardano (ada).png",
    the_coins[5]: "Payment/Photos/dash (dash).png",
    the_coins[6]: "Payment/Photos/digibyte (dgb).png",
    the_coins[7]: "Payment/Photos/dogecoin (doge).png",
    the_coins[8]: "Payment/Photos/ethereum (eth).png",
    the_coins[9]: "Payment/Photos/groestlcoin (grs).png",
    the_coins[10]: "Payment/Photos/litecoin (ltc).png",
    the_coins[11]: "Payment/Photos/polkadot (dot).png",
    the_coins[12]: "Payment/Photos/solana (sol).png",
    the_coins[13]: "Payment/Photos/stellar (xlm).png",
    the_coins[14]: "Payment/Photos/toncoin (ton).png",
    the_coins[15]: "Payment/Photos/tron (trx).png",
}
